//
// Created by ravelantunes on 10/21/17.
//

#ifndef PATH_PLANNING_CONTROLSTATE_H
#define PATH_PLANNING_CONTROLSTATE_H

enum ControlState {
  KEEP_LANE,
  PREPARE_LANE_CHANGE,
  CHANGE_LANES
};

#endif //PATH_PLANNING_CONTROLSTATE_H
